version: '3.5'

volumes:
  wf-postgres-data:
  wf-redis-data:
  wf-cache:
  wf-bundler:
  wf-elasticsearch-data:

services:
  wfapp:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: overmind start -f Procfile.development
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - wf-cache:/cache
      - wf-bundler:/usr/local/bundle/
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    depends_on:
      - wfredis
      - wfdb
      - wfelasticsearch

  wfdb:
    image: postgres:15.2
    volumes:
      - wf-postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    logging:
      driver: none

  wfredis:
    image: redis:7.0.10
    ports:
      - 26379:6379
    volumes:
      - wf-redis-data:/var/lib/redis/data:cached
    logging:
      driver: none

  wfelasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - logger.level=ERROR
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - wf-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
