version: '3.5'

volumes:
  postgres-data:
  redis-data:
  cache:
  bundler:

services:
  wfapp:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: overmind start -f Procfile.development
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - cache:/cache
      - bundler:/usr/local/bundle/
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    depends_on:
      - wfredis
      - wfdb

  wfdb:
    image: postgres:15.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    logging:
      driver: none

  wfredis:
    image: redis:7.0.10
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/var/lib/redis/data:cached
    logging:
      driver: none
